config/routes.rb
Rails.application.routes.draw do
  resources :reports
  get 'welcome/index'
  root :to =>"welcome#index"
  resources :report_types
  resources :contamination_levels
  resources :consumers
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :user
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  before_action :set_consumer, only: [:show, :edit, :update, :destroy]

  # GET /consumers
  # GET /consumers.json
  def index
    @consumers = Consumer.all
  end

  # GET /consumers/1
  # GET /consumers/1.json
  def show
  end

  # GET /consumers/new
  def new
    @consumer = Consumer.new
  end

  # GET /consumers/1/edit
  def edit
  end

  # POST /consumers
  # POST /consumers.json
  def create
    @consumer = Consumer.new(consumer_params)

    respond_to do |format|
      if @consumer.save
        format.html { redirect_to @consumer, notice: 'Consumer was successfully created.' }
        format.json { render :show, status: :created, location: @consumer }
      else
        format.html { render :new }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consumers/1
  # PATCH/PUT /consumers/1.json
  def update
    respond_to do |format|
      if @consumer.update(consumer_params)
        format.html { redirect_to @consumer, notice: 'Consumer was successfully updated.' }
        format.json { render :show, status: :ok, location: @consumer }
      else
        format.html { render :edit }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumers/1
  # DELETE /consumers/1.json
  def destroy
    @consumer.destroy
    respond_to do |format|
      format.html { redirect_to consumers_url, notice: 'Consumer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumer
      @consumer = Consumer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumer_params
      params.require(:consumer).permit(:user_id, :nombre, :correo, :telefono, :clave, :direccion)
    end
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/views/consumers/_form.html.erb
<%= form_with(model: consumer, local: true) do |form| %>
  <% if consumer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consumer.errors.count, "error") %> prohibited this consumer from being saved:</h2>

      <ul>
      <% consumer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Login Usuario" %>
    <%= form.collection_select :user_id, User.all, :id, :email %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :consumer_nombre %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo, id: :consumer_correo %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :consumer_telefono %>
  </div>

  <div class="field">
    <%= form.label :clave %>
    <%= form.text_field :clave, id: :consumer_clave %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_area :direccion, id: :consumer_direccion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/consumers/edit.html.erb
<h1>Editing Consumer</h1>

<%= render 'form', consumer: @consumer %>

<%= link_to 'Show', @consumer %> |
<%= link_to 'Back', consumers_path %>

app/views/consumers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Datos Usuario</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Telefono</th>
      <th>Clave</th>
      <th>Direccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consumers.each do |consumer| %>
      <tr>
        <td><%= consumer.user.email %></td>
        <td><%= consumer.nombre %></td>
        <td><%= consumer.correo %></td>
        <td><%= consumer.telefono %></td>
        <td><%= consumer.clave %></td>
        <td><%= consumer.direccion %></td>
        <td><%= link_to 'Ver', consumer %></td>
        <td><%= link_to 'Editar', edit_consumer_path(consumer) %></td>
        <td><%= link_to 'Eliminar', consumer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_consumer_path %>

app/views/consumers/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render 'form', consumer: @consumer %>

<%= link_to 'Regresar', consumers_path %>

app/views/consumers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @consumer.user.email %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @consumer.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @consumer.correo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @consumer.telefono %>
</p>

<p>
  <strong>Clave:</strong>
  <%= @consumer.clave %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @consumer.direccion %>
</p>

<%= link_to 'Editar', edit_consumer_path(@consumer) %> |
<%= link_to 'Regresar', consumers_path %>