config/routes.rb
Rails.application.routes.draw do
  resources :reports
  get 'welcome/index'
  root :to =>"welcome#index"
  resources :report_types
  resources :contamination_levels
  resources :consumers
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/report_types_controller.rb
class ReportTypesController < ApplicationController
  before_action :set_report_type, only: [:show, :edit, :update, :destroy]

  # GET /report_types
  # GET /report_types.json
  def index
    @report_types = ReportType.all
  end

  # GET /report_types/1
  # GET /report_types/1.json
  def show
  end

  # GET /report_types/new
  def new
    @report_type = ReportType.new
  end

  # GET /report_types/1/edit
  def edit
  end

  # POST /report_types
  # POST /report_types.json
  def create
    @report_type = ReportType.new(report_type_params)

    respond_to do |format|
      if @report_type.save
        format.html { redirect_to @report_type, notice: 'Report type was successfully created.' }
        format.json { render :show, status: :created, location: @report_type }
      else
        format.html { render :new }
        format.json { render json: @report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /report_types/1
  # PATCH/PUT /report_types/1.json
  def update
    respond_to do |format|
      if @report_type.update(report_type_params)
        format.html { redirect_to @report_type, notice: 'Report type was successfully updated.' }
        format.json { render :show, status: :ok, location: @report_type }
      else
        format.html { render :edit }
        format.json { render json: @report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_types/1
  # DELETE /report_types/1.json
  def destroy
    @report_type.destroy
    respond_to do |format|
      format.html { redirect_to report_types_url, notice: 'Report type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report_type
      @report_type = ReportType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_type_params
      params.require(:report_type).permit(:nombre, :estado)
    end
end

app/helpers/report_types_helper.rb
module ReportTypesHelper
end

app/views/report_types/_form.html.erb
<%= form_with(model: report_type, local: true) do |form| %>
  <% if report_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report_type.errors.count, "error") %> prohibited this report_type from being saved:</h2>

      <ul>
      <% report_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :report_type_nombre %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :report_type_estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/report_types/edit.html.erb
<h1>Editar Tipo de Reporte</h1>

<%= render 'form', report_type: @report_type %>

<%= link_to 'Ver', @report_type %> |
<%= link_to 'Regresar', report_types_path %>

app/views/report_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos de Reportes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @report_types.each do |report_type| %>
      <tr>
        <td><%= report_type.nombre %></td>
        <td><%= report_type.estado %></td>
        <td><%= link_to 'Ver', report_type %></td>
        <td><%= link_to 'Editar', edit_report_type_path(report_type) %></td>
        <td><%= link_to 'Eliminar', report_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Tipo de Reporte', new_report_type_path %>

app/views/report_types/new.html.erb
<h1>Nuevo Tipo de Reporte</h1>

<%= render 'form', report_type: @report_type %>

<%= link_to 'Regresar', report_types_path %>

app/views/report_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @report_type.nombre %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @report_type.estado %>
</p>

<%= link_to 'Editar', edit_report_type_path(@report_type) %> |
<%= link_to 'Regresar', report_types_path %>